version: '2.1'
services:
  db:
    image: mysql:8.0
    container_name: drscratchv3_database
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${DRSCRATCH_DATABASE_NAME}
      - MYSQL_USER=${DRSCRATCH_DATABASE_USER}
      - MYSQL_ROOT_PASSWORD=${DRSCRATCH_DATABASE_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${DRSCRATCH_DATABASE_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 40s
      retries: 10
    volumes:
      - dbdata:/var/run/mysqld
  getsb3:
    build: ./scratchapi
    ports:
      - "3000:3000"
  tor_proxy:
    build: ./tor_proxy
    command: sh -c "tor"
    container_name: tor_proxy
    ports:
      - "9050:9050"
  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - .:/var/www
    ports:
      - "5672:5672"
      - "15672:15672"
  celery:
    build: .
    command: celery -A drScratch worker --loglevel=debug
    volumes:
      - .:/var/www
    depends_on:
      - rabbitmq
  web:
    build: .
    volumes:
      - .:/var/www
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: drscratchv3_django
    user: root
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    stdin_open: true
    tty: true
    depends_on:
      db:
        condition: service_healthy
      tor_proxy:
        condition: service_started
      rabbitmq:
        condition: service_started  
volumes:
  dbdata: