# Generated by Django 4.1.7 on 2024-05-03 09:47

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Coder',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('birthmonth', models.CharField(max_length=100)),
                ('birthyear', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('gender_other', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('img', models.ImageField(default='app/images/drScratch.png', upload_to='img/')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('text', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CSVs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('directory', models.CharField(max_length=100)),
                ('organization', models.CharField(default='drscratch', max_length=100)),
                ('coder', models.CharField(default='drscratch', max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Discuss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.TextField()),
                ('date', models.DateTimeField()),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('hashkey', models.TextField()),
                ('img', models.ImageField(default='app/images/drScratch.png', upload_to='img/')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationHash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashkey', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_score', models.TextField()),
                ('basic', models.TextField(default='')),
                ('development', models.TextField(default='')),
                ('master', models.TextField(default='')),
                ('daily_projects', models.TextField(default='')),
                ('parallelism', models.IntegerField(default=0)),
                ('abstraction', models.IntegerField(default=0)),
                ('logic', models.IntegerField(default=0)),
                ('synchronization', models.IntegerField(default=0)),
                ('flowControl', models.IntegerField(default=0)),
                ('userInteractivity', models.IntegerField(default=0)),
                ('dataRepresentation', models.IntegerField(default=0)),
                ('deadCode', models.IntegerField(default=0)),
                ('duplicateScript', models.IntegerField(default=0)),
                ('spriteNaming', models.IntegerField(default=0)),
                ('initialization', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TokenCoder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('surname', models.CharField(max_length=100, null=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('email', models.TextField()),
                ('hashkey', models.TextField()),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('organization', models.CharField(default='drscratch', max_length=100)),
                ('coder', models.CharField(default='drscratch', max_length=100)),
                ('method', models.CharField(max_length=100)),
                ('time', models.DateField()),
                ('language', models.TextField(default='en')),
                ('score', models.IntegerField()),
                ('abstraction', models.IntegerField()),
                ('parallelization', models.IntegerField()),
                ('logic', models.IntegerField()),
                ('synchronization', models.IntegerField()),
                ('flowControl', models.IntegerField()),
                ('userInteractivity', models.IntegerField()),
                ('dataRepresentation', models.IntegerField()),
                ('spriteNaming', models.IntegerField()),
                ('initialization', models.IntegerField()),
                ('deadCode', models.IntegerField()),
                ('duplicateScript', models.IntegerField()),
                ('coder_token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.tokencoder')),
            ],
        ),
    ]
