# Generated by Django 4.1.7 on 2024-02-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_merge_20180924_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coder',
            name='img',
            field=models.ImageField(default='app/images/drScratch.png', upload_to='app/images/'),
        ),
        migrations.AlterField(
            model_name='csvs',
            name='coder',
            field=models.CharField(default='drscratch', max_length=100),
        ),
        migrations.AlterField(
            model_name='csvs',
            name='organization',
            field=models.CharField(default='drscratch', max_length=100),
        ),
        migrations.AlterField(
            model_name='file',
            name='coder',
            field=models.CharField(default='drscratch', max_length=100),
        ),
        migrations.AlterField(
            model_name='file',
            name='language',
            field=models.TextField(default='en'),
        ),
        migrations.AlterField(
            model_name='file',
            name='organization',
            field=models.CharField(default='drscratch', max_length=100),
        ),
        migrations.AlterField(
            model_name='organization',
            name='img',
            field=models.ImageField(default='app/images/drScratch.png', upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='basic',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='stats',
            name='daily_projects',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='stats',
            name='development',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='stats',
            name='master',
            field=models.TextField(default=''),
        ),
    ]
