# Generated by Django 4.1.7 on 2024-04-30 13:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_alter_coder_img_alter_csvs_coder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenCoder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.AlterField(
            model_name='coder',
            name='img',
            field=models.ImageField(default='app/images/drScratch.png', upload_to='img/'),
        ),
    ]
