# Generated by Django 4.1.7 on 2024-05-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_alter_coder_img_alter_csvs_coder_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='parallelization',
            new_name='parallelism',
        ),
        migrations.AlterField(
            model_name='coder',
            name='img',
            field=models.ImageField(default='app/images/drScratch.png', upload_to='img/'),
        ),
    ]
