# Generated by Django 4.1.7 on 2024-06-08 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_alter_coder_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stats',
            old_name='parallelism',
            new_name='parallelization',
        ),
    ]
