# Generated by Django 4.1.7 on 2024-04-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_tokencoder_alter_coder_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokencoder',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tokencoder',
            name='surname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
