# Generated by Django 4.1.7 on 2024-05-25 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_rename_parallelism_stats_parallelization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='file',
            table='app_file',
        ),
    ]
