# Generated by Django 4.1.7 on 2024-04-30 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_tokencoder_name_tokencoder_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='coder_name',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='files_as_coder_name', to='app.tokencoder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='coder_token',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tokencoder'),
        ),
    ]
