# Generated by Django 4.1.7 on 2024-04-30 15:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_file_coder_name_file_coder_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='coder_name',
        ),
        migrations.AddField(
            model_name='file',
            name='coder_username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='files_as_coder_username', to='app.tokencoder', to_field='username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='coder_token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files_as_coder_token', to='app.tokencoder', to_field='token'),
        ),
        migrations.AlterField(
            model_name='tokencoder',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
