# Generated by Django 4.1.7 on 2024-05-25 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_alter_file_options_alter_file_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={},
        ),
        migrations.AlterModelTable(
            name='file',
            table=None,
        ),
    ]
