# Generated by Django 4.1.7 on 2024-06-06 09:31

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_rename_parallelizations_file_parallelization'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchCSV',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filepath', models.CharField(max_length=100)),
                ('num_projects', models.IntegerField()),
                ('max_points', models.FloatField()),
                ('points', models.FloatField()),
                ('max_logic', models.FloatField()),
                ('logic', models.FloatField()),
                ('max_parallelization', models.FloatField()),
                ('parallelization', models.FloatField()),
                ('max_data', models.FloatField()),
                ('data', models.FloatField()),
                ('max_synchronization', models.FloatField()),
                ('synchronization', models.FloatField()),
                ('max_userInteractivity', models.FloatField()),
                ('userInteractivity', models.FloatField()),
                ('max_flowControl', models.FloatField()),
                ('flowControl', models.FloatField()),
                ('max_abstraction', models.FloatField()),
                ('abstraction', models.FloatField()),
                ('max_math_operators', models.FloatField()),
                ('math_operators', models.FloatField()),
                ('max_motion_operators', models.FloatField()),
                ('motion_operators', models.FloatField()),
                ('mastery', models.CharField(max_length=50)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
