# Generated by Django 4.1.7 on 2024-06-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_batchcsv'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchcsv',
            name='task_time',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
