# Generated by Django 4.1.7 on 2024-10-28 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_alter_batchcsv_task_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchcsv',
            name='math_operators',
        ),
        migrations.RemoveField(
            model_name='batchcsv',
            name='max_math_operators',
        ),
        migrations.RemoveField(
            model_name='batchcsv',
            name='max_motion_operators',
        ),
        migrations.RemoveField(
            model_name='batchcsv',
            name='motion_operators',
        ),
    ]
