# Generated by Django 4.1.7 on 2024-07-31 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_alter_batchcsv_task_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='creation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='modified_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
