# Generated by Django 4.1.7 on 2025-01-02 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_alter_batchcsv_task_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='abstraction',
        ),
        migrations.RemoveField(
            model_name='file',
            name='dataRepresentation',
        ),
        migrations.RemoveField(
            model_name='file',
            name='flowControl',
        ),
        migrations.RemoveField(
            model_name='file',
            name='logic',
        ),
        migrations.RemoveField(
            model_name='file',
            name='parallelization',
        ),
        migrations.RemoveField(
            model_name='file',
            name='synchronization',
        ),
        migrations.RemoveField(
            model_name='file',
            name='userInteractivity',
        ),
        migrations.AddField(
            model_name='file',
            name='batch',
            field=models.UUIDField(default=None, editable=False),
        ),
        migrations.AddField(
            model_name='file',
            name='metrics',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='file',
            name='vanilla_metrics',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='batchcsv',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
