# Generated by Django 4.1.7 on 2025-01-02 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_remove_file_abstraction_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='batch',
            new_name='batch_id',
        ),
    ]
