# Generated by Django 4.1.7 on 2024-07-31 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_alter_activity_id_alter_comment_id_alter_csvs_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='creation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='modified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
