# Generated by Django 4.1.7 on 2025-01-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_rename_batch_file_batch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='batch_id',
            field=models.UUIDField(default=None, editable=False, null=True),
        ),
    ]
