# Generated by Django 4.1.7 on 2024-07-31 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_alter_file_creation_date_alter_file_modified_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='scratch_project_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
