# Generated by Django 4.1.7 on 2025-01-02 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_alter_file_batch_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='metrics',
            new_name='extended_metrics',
        ),
    ]
