# Generated by Django 4.1.7 on 2024-07-31 10:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_file_scratch_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4),
        ),
    ]
