# Generated by Django 4.1.7 on 2025-02-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_rename_max_parallelization_batchcsv_max_parallelism_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='backdropNaming',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
