# Generated by Django 4.1.7 on 2024-07-31 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_file_file_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='full_analysis',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
