# Generated by Django 4.1.7 on 2024-08-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_file_full_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='scratch_author',
            field=models.CharField(default='drscratch', max_length=100),
        ),
    ]
