# Generated by Django 4.1.7 on 2024-08-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_file_scratch_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='project_parent_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
